# Run meta
seed: 0
basename: default  # Base name identifying the run
device: ~  # "cpu" or "cuda"; defaults to cuda if available
dry_run: false  # Dry run for debugging
verbosity: 1  # [0, 1, 2] of increasing verbosity
disable_wandb: false  # Disable WandB online integration
model: MLP
pretrained: False

testinit: False
