# Run meta
seed: 0
basename: baseline # wandb run name.
device: ~  # "cpu", "mps", or "cuda"; defaults to cuda if available
dry_run: false  # Dry run for debugging
verbosity: 1  # [0, 1, 2] of increasing verbosity
disable_wandb: false  # Disable WandB online integration
model: EleutherAI/pythia-14m
baseline_metrics_path: baseline # Path to save metrics
run_baseline: true # If True, calculates metric on the base model. If False, applies unadapt and calculate metric on unadapt model
testinit: false
# Hydra
hydra:
  # Change hydra's default that suppresses traceback
  job_logging:
    full_stack_trace: true
