# Special hydra param, inherit defaults from base_config.yaml
defaults:
  - base_config
  # Notice the keywords below match config dirs
  - unadapt: gradient
  - finetune: fashion
  - _self_

# Base name identifying the run
basename: mnist
early_terminate: ~
